### ISSUE TITLE
Marzo 2018

### ISSUE THREAD

**Issue by gcanti** [gcanti/who-is-hiring-italy#1]
Please state the job location and include the keywords REMOTE, INTERNS and/or VISA when the corresponding sort of candidate is welcome. When remote work is not an option, include ONSITE.
Please only post if you personally are part of the hiring company—no recruiting firms or job boards. Only one post per month, please. If it isn't a household name, explain what your company does.

Commenters: please don't reply to job posts to complain about something. It's off topic here.

Readers: please only email submitters if you personally are interested in the job—no recruiters or sales calls.

**Comment by dbertella** [comment]
[Revolut](https://www.revolut.com/de/careers?lang=en#senior-front-end-developerlondon-united-kingdom) - London - ONSITE

**Comment by XVincentX** [comment]
[Uala.it](https://www.uala.it) - Milano - Frontend developer (React) - REMOTE

**Comment by dlion** [comment]
[XPeppers](https://www.xpeppers.com/carriere/) - Milano/Trento/Roma - ONSITE

**Comment by gabro** [comment]
[buildo](http://buildo.io/careers) - Milano - ONSITE

**Comment by dharmastyle** [comment]
[basilico](https://www.basili.co) – Brescia – Frontend Developer (WebGL) – ONSITE

**Comment by gcanti** [comment]
Tratto da [Ask HN: Who is hiring? (March 2018)](https://news.ycombinator.com/item?id=16492994)

Prima Assicurazioni | Software Engineer | Milano, ITALY | Full-time | ONSITE
We are looking for a Software Engineer with a strong passion for excellent coding and willing to learn powerful and cutting-edge technologies.

REQUIREMENTS: You are skilled in at least one among these programming languages: Elixir, PHP, Ruby, Javascript. You have a strong experience in unit and functional testing. You are experienced in working with web application framework such as Symfony or Phoenix.

NICE TO HAVE: Experience with functional programming. Knowledge of Elixir and Elm. Knowledge of RabbitMQ, Elasticsearch, Datadog. Experience in working with microservice-oriented infrastructure.

BENEFITS: Unlimited budget for hardware. Opportunity to participate to dev conference (e.g. ElixirConf, CloudConf, Code BEAM Lite, Milano JS). Amazing location: 50 meters from the Piazza Duomo, Milano.

If you’re interested in joining our team, send us an email with your CV at jobs@prima.it

**Comment by ibbatta** [comment]
[Docsity](https://www.docsity.com/it/) — Roma — Frontend Developer (React) — ONSITE

**Comment by xpmatteo** [comment]
ThoughtWorks Italia cerca:

- [Application Developers](https://www.thoughtworks.com/jobs/903488)
- [Business Analysts](https://www.thoughtworks.com/jobs/268325)
- [Quality Assurance Analysts](https://www.thoughtworks.com/jobs/268333)

Per tutte le posizioni, ahimé, è richiesta la conoscenza della lingua italiana. Per questo scrivo l'annuncio in italiano.

Il lavoro è in ogni caso ONSITE, nel senso che si va a lavorare a casa del cliente.  La gran parte del lavoro oggi è a Milano, Roma e Torino, ma non si sa mai dove sarà la sede del prossimo cliente.

**Comment by gcanti** [comment]
A tutti: potete rinnovare gli annunci nel 3D di Aprile (aperto da @dlion)
