### ISSUE TITLE
Marzo 2019

### ISSUE THREAD

**Issue by XVincentX** [gcanti/who-is-hiring-italy#13]

**Comment by XVincentX** [comment]
Uala.it - Milano - Frontend developer (React) - REMOTE. Contattatemi su Twitter o via eMail

**Comment by alsoknownasdrew** [comment]
# Facile.it

**Milan, Italy** (ONSITE + REMOTE)

In Facile.it stiamo cercando:

- Senior Frontend Developer
- Backend PHP Developer
- Android Developer
- DevOps Engineer
- Software QA Specialist
- Data Engineer

**Cagliari, Italy** (ONSITE + REMOTE)

- Backend PHP Developer

**Comment by testinaweb** [comment]
Yumpingo.com

Remote 99% (2/4 volte all'anno trasferta pagata a Londra per 3 giorni)

Posizioni aperte:
- 1 Senior frontend developer (Angular 2-7)
- 2 Backend developer / Software engineer (typescript, nestJs, mysql)
- 1 Software QA Specialist

Inglese richiesto e fondamentale

scrivete a manuel@yumpingo.com

**Comment by ohelixa** [comment]
## Helixa.ai

**Milan, Italy** (no remote)

Siamo alla ricerca di un Back End Developer con queste caratteristiche:

- Extensive knowledge of Java
- Good understanding of Javascript and possibly experience with Node.js
- Experience with both SQL and NoSQL databases. (MongoDB, Elasticsearch)

Molto bello se:
- Experience with of AWS (EC2, S3, Lambda, Firehose)
- Experience with Microservices architecture
- Experience with Container Architecture (Docker, Kubernetes)

scrivere a : oassadi@helixa.ai

**Comment by magobaol** [comment]
# Hootsuite/AdEspresso

Siamo alla ricerca di un/una frontend developer per la nostra sede di Roma.

Lavoriamo in piccoli team su vari progetti che ruotano intorno ad AdEspresso (www.adespresso.com) e a Hootsuite (www.hootsuite.com).
Adottiamo le buone pratiche dello sviluppo agile: sprint brevi, rilasci frequenti, test automatici e code review, per citarne solo alcune.

Cerchiamo un/una frontender in gamba, meglio se ha già esperienza in React.JS e Redux.
La RAL è tra i 45.000 e i 50.000 euro.
La sede si trova a Roma Termini, quindi facilmente raggiungibile sia dalla città che da fuori.

Potete sottoporre la vostra condidatura direttamente qui: https://careers.hootsuite.com/global/en/job/1574984/Software-Developer

Per qualsiasi informazioni, scrivetemi pure su twitter @magobaol o via email a mionome.miocognome@hootsuite.com.

**Comment by Giako** [comment]
### [Stentle](https://www.stentle.com)

Cerchiamo un/una **Frontend Developer**, onsite nella nostra sede di Milano (zona Garibaldi). Maggiori informazioni [qui](https://www.stentle.com/careers/web-developer-frontend/).

- **Tecnologie**: React.js, React Native, Redux, Typescript, Laravel.
- **Metodologia di lavoro**: agile (principalmente Scrum/Kanban)
- **Plus**: Docker, native development in Android e/o iOS, esperienza di gestione di piccoli team

Per maggiori informazioni contattatemi pure su [Twitter](https://twitter.com/Giako87) oppure potete inviare una candidatura a careers@stentle.com.
