### ISSUE TITLE
Maggio 2019

### ISSUE THREAD

**Issue by lucacavallaro** [gcanti/who-is-hiring-italy#15]
# PED

In PED (https://ped.company/) stiamo cercando:

**Milano**
* [Frontend Developer](https://ped.company/careers?job=frontendmilano#position) (Junior, Mid, Senior)
* [iOS Developer](https://ped.company/careers?job=iosmilano#position)

**Catania**
* [Frontend Developer](https://ped.company/careers?job=frontendcatania#position) (Junior, Mid, Senior)
* [iOS Developer](https://ped.company/careers?job=ioscatania#position)

**Ragusa**
* [Frontend Developer](https://ped.company/careers?job=frontendragusa#position) (Junior, Mid, Senior)
* [iOS Developer](https://ped.company/careers?job=iosragusa#position)

Altre posizioni aperte su https://ped.company/careers

**Comment by alsoknownasdrew** [comment]
# Facile.it

(ONSITE + REMOTE)

In [Facile.it](https://engineering.facile.it/) stiamo cercando:

**Milano**

- [Senior Frontend Developer](https://inrecruiting.intervieweb.it/facileit/jobs/senior_frontend_engineer_60874/it/)
- [PHP Backend Developer](https://inrecruiting.intervieweb.it/facileit/jobs/php_backend_developer_45888/it/)
- [Full Stack Web Developer](https://inrecruiting.intervieweb.it/facileit/jobs/prova_29824/it/)
- [DevOps Engineer](https://inrecruiting.intervieweb.it/facileit/jobs/devops_engineer_52226/it/)
- [Data Scientist](https://inrecruiting.intervieweb.it/facileit/jobs/data_scientist_62258/it/)
- [Data Engineer](https://inrecruiting.intervieweb.it/facileit/jobs/data_engineer_62259/it/)

**Cagliari**

- [PHP Backend Developer](https://inrecruiting.intervieweb.it/facileit/jobs/php_backend_developer_64020/it/)
- [Software QA Specialist](https://inrecruiting.intervieweb.it/facileit/jobs/software_qa_specialist_64376/it/)

**Comment by SirStoke** [comment]
# Efficiam

(100% remote)

In [Efficiam](https://efficiam.com) stiamo cercando developers Scala e Frontend: [qui](https://efficiam.com/careers) per piu' info

**Comment by andreacorradi** [comment]
# imille

In [imille.agency](https://www.imille.agency/it/) stiamo cercando un [creative front end developer](https://www.imille.agency/it/careers) (Mid, Senior) su **Milano**
