### ISSUE TITLE
Guidelinea?

### ISSUE THREAD

**Issue by ibbatta** [gcanti/who-is-hiring-italy#2]
Al fine di evitare i soliti lavori fatti alla "carlona" lasciati in mano alla variegata fauna di utenti, sarebbe utile stabilire delle guidelinea sui commenti, tipo:

**Titolo**
_Azienda_

```Breve descrizione possibilmente farcita di dettagli tecnici e ral```

che ne dici?

**Comment by dbertella** [comment]
ma tu come ci sei arrivato qui? ahah stiamo discutendo appunto questo, un momento!

**Comment by Slumber86** [comment]
Penso che il testo che usano su HN sia perfetto:
`Please state the job location and include the keywords REMOTE, INTERNS and/or VISA when the corresponding sort of candidate is welcome. When remote work is not an option, include ONSITE.
Please only post if you personally are part of the hiring company—no recruiting firms or job boards. Only one post per month, please. If it isn't a household name, explain what your company does.

Commenters: please don't reply to job posts to complain about something. It's off topic here.

Readers: please only email submitters if you personally are interested in the job—no recruiters or sales calls.`

**Comment by ibbatta** [comment]
Sono un attento osservatore della mia timeline di github ahahah <3
(chiudo la issue allora)
