### ISSUE TITLE
Require info and salary range for each post

### ISSUE THREAD

**Issue by luigiberrettini** [gcanti/who-is-hiring-italy#4]
It would be nice to give an added value service with respect to job boards making cmpulsory for job posts to include:
 - a description of the role (not having to go to the careers section of the company site would be great)
 - a salary range on offer

**Comment by gcanti** [comment]
@luigiberrettini non credo sia strettamente necessario rendere alcune informazioni obbligatorie, se un'azienda non mette informazioni vitali come ruolo e salario, il suo annuncio avrà un impatto minore rispetto agli altri annunci. E' interesse prima di tutto dell'azienda fare in modo che l'annuncio sia appetibile.

**Comment by luigiberrettini** [comment]
In teoria sono d'accordo in pratica la maggior parte di annunci sono senza informazioni perchè comunque è il candidato ad essere "il disperato che cerca lavoro"

Un dev che propone un "servizio" come questo IMHO dovrebbe cercare di offrire qualcosa di diverso dalle centinaia di job sites esistenti e anche preparare un futuro migliore, come accade sul gruppo FB di WebDeBs, ma questo è solo il mio pensiero, che come tale può essere condiviso o meno.

**Comment by gcanti** [comment]
@luigiberrettini a scanso di equivoci, questo nasce come esperimento di **autogestione** degli utenti di italiajs per dirottare qui gli annunci di lavoro che nello slack non sono permessi, io ho solo fatto una proposta e aperto un repo.

**Comment by luigiberrettini** [comment]
Mi accorgo che la mia frase poteva sembrare avere un tono di giudizio, ma non era mia intenzione: volevo solo dare un feedback sulle aspettative di chi cerca lavoro che fa fatica a filtrare gli annunci per mancanza di info esaustive e allo stesso tempo coincise

Non sapevo/avevo capito da dove era nato il repo, grazie per il chiarimento
