### ISSUE TITLE
Aprile 2018 ?

### ISSUE THREAD

**Issue by dlion** [gcanti/who-is-hiring-italy#5]
No April's thread? 😢

**Comment by gabro** [comment]
Now there's one! ;)

[buildo](http://buildo.io/careers) - Milano - ONSITE

**Comment by ibbatta** [comment]
[Docsity](https://www.docsity.com/it/) — Roma — Frontend Developer (React) — ONSITE

**Comment by dlion** [comment]
[XPeppers](https://www.xpeppers.com/carriere/) - Milano/Trento/Roma/Lugano - ONSITE

**Comment by xpmatteo** [comment]
[ThoughtWorks Italia](https://www.thoughtworks.com/jobs/903488) Working at the customer's place, wherever in Italy that may be -- ONSITE -- Italian speaking skillz required

**Comment by Slumber86** [comment]
@dlion il certificato SSL scaduto non fa venire molta voglia di applicare <3

**Comment by dlion** [comment]
@Slumber86 Fatalità vuole che tu abbia aperto il sito proprio oggi che lo stavamo aggiornando, verrà fixato asap, grazie ❤️

**Comment by Giako** [comment]
[Stentle](https://stentle.com/careers/) - Milano - ONSITE 
Especially we are looking for [Java back-end devs](https://stentle.com/careers/java-backend-developer/) and [Front-end devs] (https://stentle.com/careers/web-developer-frontend/) (Javascript | PHP)

**Comment by XVincentX** [comment]
[Uala.it](https://www.uala.it) - Milano - Frontend developer (React) - REMOTE 

P.S: Penso mi scriverò un bot per mettere l'annuncio in automatico ogni mese.

**Comment by JeremyRms** [comment]
ZenRooms.com - Bangkok - Full Stack Developer (PHP/NodeJs/React) - ONSITE

**Comment by lastguest** [comment]
## [Caffeina](https://caffeina.com)
Parma - ONSITE

Stiamo cercando [Backend Engineer](https://caffeina.com/jobs/technology/backend-developer) (PHP7 | Go | Node.js) e [Frontend Engineer](https://caffeina.com/jobs/technology/frontend-developer) (React) che entrino a far parte del nostro team Technology.

📰 Jobs : https://caffeina.com/jobs/technology
🐦 Twitter : https://twitter.com/caffeinadevs
💻 GitHub : https://github.com/caffeinalab

**Comment by Slumber86** [comment]
@gcanti dovremmo chiuderla
