### ISSUE TITLE
Maggio 2018

### ISSUE THREAD

**Issue by dlion** [gcanti/who-is-hiring-italy#6]
[XPeppers](https://www.xpeppers.com/carriere/) - Milano/Trento/Roma/Lugano - ONSITE

**Comment by ibbatta** [comment]
[Docsity](https://www.docsity.com/it/) — Roma — Junior / Mid Frontend Developer (React) — ONSITE

**Comment by mpangrazzi** [comment]
[Wonderflow](https://www.wonderflow.co) - Trento - ONSITE

**Comment by lastguest** [comment]
## [Caffeina](https://caffeina.com)
🗺 [Parma](https://goo.gl/maps/S9vPddffriw) - ONSITE

Stiamo cercando [Backend Engineer](https://caffeina.com/jobs/technology/backend-developer) (PHP7 | Go | Node.js) e [Frontend Engineer](https://caffeina.com/jobs/technology/frontend-developer) (React) che entrino a far parte del nostro team Technology.

📰 Jobs : https://caffeina.com/jobs/technology
🐦 Twitter : https://twitter.com/caffeinadevs
💻 GitHub : https://github.com/caffeinalab

**Comment by xpmatteo** [comment]
[ThoughtWorks Italia](https://www.thoughtworks.com/jobs/903488) Working at the customer's place, wherever in Italy that may be -- ONSITE -- Italian speaking skillz required

**Comment by boris-borisov** [comment]
Hi everyone!

Would you like to find a remote full-time job?

We’re launching a platform that makes it easy. When you sign-up for RemoteMore, top companies interested in remote hiring will be able to find your profile and invite you for interviews.

Learn more and sign-up on this URL -->> https://goo.gl/xeksaS

**Comment by lifeisfoo** [comment]
[Bemind](http://www.bemind.me/) - Italia- [Frontend dev](http://jobs.bemind.me/o/js-frontend-developer-reactredux-mf) (React/Redux/JS) - REMOTE

**Comment by ivanopagano** [comment]
Warda, zona Padova:
Stiamo cercando anche uno [Scala Sw Engineer](https://www.linkedin.com/jobs/view/688194256/)… Ne conoscete qualcuno?

**Comment by zuc** [comment]
## [ProntoPro](https://www.prontopro.it/)

Milano, Stazione Centrale

Team technology di 15+ engineers. Cerchiamo:

- **[Senior Systems Engineer/DevOps](https://prontopro.recruiterbox.com/jobs/fk0fstt/)** (aws, kubernetes, ansible, terraform)
- **[Backend Engineer](https://prontopro.recruiterbox.com/jobs/fk0hzoz/)** (symfony, php7, nodejs, golang, python)
- **[Frontend Engineer](https://prontopro.recruiterbox.com/jobs/fk0hzbs/)** (react, redux, react native)

Get in touch!
https://prontopro.recruiterbox.com

**Comment by intrip** [comment]
## [Iubenda](https://www.iubenda.com)

Milano / Bologna / Remote

- [Senior ROR dev](https://www.iubenda.com/en/help/1812-work-with-us#rordev) 
- [Senior JS dev](https://www.iubenda.com/en/help/1812-work-with-us#jsdev) 
- [Devops Engineer](https://www.iubenda.com/en/help/1812-work-with-us#devops)
