### ISSUE TITLE
Giugno 2018

### ISSUE THREAD

**Issue by christian-fei** [gcanti/who-is-hiring-italy#7]
[Wonderflow](https://www.wonderflow.co/) - Trento - Agile Full Stack Developer - ONSITE

![wonderflow-logo-300](https://user-images.githubusercontent.com/2662706/41219132-b93c94a2-6d5d-11e8-9f6c-4f23fd135e35.png)

[Job offer](https://www.wonderflow.co/jobs/full-stack-developer/) 📋

**Comment by hpatoio** [comment]
[Musement.com](https://www.musement.com/it/chi-siamo-p/) - Milano

Stiamo cercando persone con qualsiasi livello di esperienza da inserire e far crescere nel nostro team. 

L'applicativo principale (AKA "Il monolite") è scritto in Symfony ma lo stiamo spezzando in diversi servizi sviluppati in PHP e NodeJs. 

Bonus:
 - TechFriday - Dove potrai sperimentare e/o studiare 
 - Smart working
 - Ambiente internazionale (11 nazionalità) e giovane

Per qualsiasi informazione/curiosità potete scrivermi via email a simone.fumagalli@musement.com 
Per inviare la candidatura -> https://bit.ly/2NiPRw9

**Comment by Giako** [comment]
[Stentle](https://stentle.com/) - Milano - ONSITE 

![Stentle logo](https://www.stentle.com/wp-content/themes/stentle/dist/images/logo-stentle-az.png)

We are looking for:
[Java back-end devs](https://stentle.com/careers/java-backend-developer/) (Java | MongoDB | Docker | Spring)
[Front-end devs](https://stentle.com/careers/web-developer-frontend/) (Javascript | PHP | React | Laravel)
