### ISSUE TITLE
Luglio 2018

### ISSUE THREAD

**Issue by agos** [gcanti/who-is-hiring-italy#8]
# [Goldmoney](https://goldmoney.com) - Milano - Frontend Engineer - Onsite

![goldmoney-logo](https://user-images.githubusercontent.com/111486/42383167-b87f70f6-8136-11e8-9f16-27b24910db50.png)

## Job Description

As one of the fastest growing cryptocurrency and precious metals custodians on the planet, we're looking for a passionate Front-end or Full-stack Engineer (Junion & Senior positions available) to help ensure that we can continue to offer our 1 million+ customers the best-possible experience. Goldmoney is at the cutting edge of the global fintech space, and this is a great opportunity for a driven, talented individual.

You'll be joining a small and dedicated team, helping to design, develop, and deliver products across an ever-increasing spectrum. You'll be immersed in a mixed Angular 1.x & React environment, working with our Engineering and Design teams directly. Day-to-day tasks will include implementation of new user-facing features, addressing and improving UX issues, and supporting staff on creating tools to help us reach our lofty goals.

## What We Offer

- Competitive compensation based on your actual experience;
- Performance-based employee stock options plan;
- The opportunity to be part of an international game-changer;
- Office conveniently located near the Fintech District in Milan, Italy.

### Skills & Requirements

- Bachelor's Degree in Computer Science or equivalent discipline;
- Proven track record in writing Angular 1.x applications;
- Exposure to and experience in working with React;
- You've mastered npm, gulp, webpack, yarn, and are comfortable with all of the day-to-day tooling a typical front-end engineer is exposed to;
- Experience working with git (you have an active Github profile);
- You know Sass and use it on a regular basis;
- You've built complex user interfaces in Angular and are comfortable working with directive-driven applications;
- Problem solving skills are a must - you must love a challenge and must be able to grind through the tough problems we face every day;
- Working proficiency and communication skills in verbal and written English;
- Committed, reliable, and flexible.

### Nice to Haves
- Previous exposure to Typescript
- Full-stack capabilities, with experience in Scala backend development is a huge plus;
- Experience in a Test Driven Design environment;
- A passion for finance technology and/or cryptography;
- Start-up experience or experience working on a small, dedicated team.

### Our products
- [Goldmoney](https://goldmoney.com)
- [Menē](https://mene.com)
- [Blockvault](https://blockvault.ch)

If the above sounds interesting, contact us at milano@goldmoney.com! You can also find me as @agos on MilanoJS Slack

**Comment by davidcorehab** [comment]
**CoRehab - empower your training**

CoRehab (www.corehab.it) è un'azienda emergente che vuole cambiare il paradigma della terapia fisica con dispositivi wearable e software altamente innovativi, standardizzando i programmi di riabilitazione creati con big data e coinvolgendo pazienti riabilitativi in clinica e a domicilio.
CoRehab vende i propri prodotti sul mercato internazionale con tutte le certificazioni necessarie e con grande consenso da parte di medici e pazienti. 
Stiamo attualmente ricercando nuove risorse per allargare il nostro team, diventare così il player più importante sul mercato globale e rivoluzionare il modo in cui oggi conosciamo la terapia fisica.

Stiamo cercando uno sviluppatore responsabile della realizzazione di applicazioni di riabilitazione per varie piattaforme target basandosi sul framework Unity. Le applicazioni sono controllate da sensori bluetooth di movimento proprietari e sono costruite per funzionare come client per un server basato su cloud. Le responsabilità principali saranno quelle di implementare le applicazioni per i pazienti sui quali si eseguono diversi tipi di esercizi con i sensori, in base ai requisiti dei fisioterapisti e clinici con cui ci rapportiamo e a quelli di una buona esperienza utente e interfaccia utente lean.

**Responsabilità**

- Implementare applicazioni robuste
- Tradurre le specifiche di progettazione in moduli funzionali
- Comunicare con gli altri membri del team per stabilire una pipeline efficace e integrare le risorse multimediali
- Progettare, costruire e mantenere codice efficiente, riutilizzabile e affidabile
- Garantire le migliori prestazioni, qualità e reattività delle applicazioni
- Aiutare a mantenere la qualità del codice, l'organizzazione e l'automatizzazione

**Abilità richieste o desiderate**

- Buona conoscenza del framework Unity (con C #) che include esperienze sulla gestione di texture, video, stili GUI e comunicazione web
- Esperienza con lo sviluppo mobile (iOS/Android)
- Familiarità con i più moderni design pattern e architectural pattern

_Rappresentano inoltre un plus:_
- precedenti esperienze con .NET
- precedenti esperienzedi interazione con device bluetooth
- familiarità con lo sviluppo agile
- conoscenza di sistemi UNIX
- conoscenza della lingua inglese

**Cosa offriamo**

Un contratto di lavoro a tempo indeterminato con una paga competitiva e adeguata alla tua esperienza e eventuali incentivi per il trasferimento.
Siamo disposti anche a valutare la possibilità di smart working (lavoro da remoto) dopo un periodo di affiancamento in azienda.

**Diventare uno di noi significa...**
Lavorare in CoRehab significa entrare a far parte di un team giovane, coeso e di altissima qualità, composto da sviluppatori, ingegneri e manager che lavorano ogni giorno fianco a fianco e tutti sono protagonistidi un'azienda internazionale in continua crescita.
La nostra sede di lavoro è a Trento, un luogo meraviglioso dove puoi trovare la miglior qualità della vita in Italia. Trento è una città dinamica e in continua crescita, con ricerca e tecnologia che rappresentano uno dei primi driver economici, ma dove in pochi minuti puoi raggiungere laghi e montagne tra le più belle al mondo.

**Manda il tuo CV a _info at corehab.com_**
