### ISSUE TITLE
Ottobre 2018

### ISSUE THREAD

**Issue by hpatoio** [gcanti/who-is-hiring-italy#9]
Ciao, Musement.com è stata recentemente comperata dal colosso tedesco del turismo TUI 

Qui il comunicato TUI https://www.tuigroup.com/en-en/media/press-releases/2018/2018-09-14-tui-acquires-italian-technology-start-up-musement e qui qualche articolo della stampa italiana:

- https://www.ilsole24ore.com/art/tecnologie/2018-09-14/arriva-l-exit-musement-acquisizione-milionaria-colosso-tui-group-125515.shtml
- https://startupitalia.eu/97026-20180914-musement-acquisita-dal-colosso-del-turismo-tui-group

TUI, alcuni numeri :

- 67,000 employees
- 1,800 travel agencies
- 6 airlines with 130 aircraft
- 300 hotels and resorts
- 18 miliardi di € di fatturato

Potete leggere di più qui https://en.wikipedia.org/wiki/TUI_Group

Stiamo cercando figure sia per backend (PHP/Symfony) che per la parte frontend (Node/VueJS) di qualsiasi seniority. Attualmente l'area sviluppo è formata da 15 persone.

Non vi sto ad elencare i requisiti singolarmente. Se siete giovani e con voglia di imparare troverete un buon posto dove crescere, se avete esperienza troverete nuovi colleghi con cui confrontarvi e condividere le vostre conoscenze. 

Qui maggiori dettagli https://gist.github.com/hpatoio/0d058bca6e09718ae9086df7a0fdd4b9

Se avete domande o per candidarvi scrivetemi a simone.fumagalli @ musement.com

Mercoledì ospiteremo un evento per l'hacktoberfest. Se volevete venire a trovarci trovate i dettagli qui https://www.meetup.com/it-IT/MilanoPHP/events/255259897/

**Comment by lifeisfoo** [comment]
![senza-titolo-12](https://dgivdslhqe3qo.cloudfront.net/sites/4022/normal_share_image_1539704225.png)


In **Bemind** cerchiamo una nuova persona da inserire nel nostro team.
Si può lavorare al **100% da remoto** o in uno dei nostri spazi a **Biella** o **Milano**. 
Trovate tutti i dettagli nell'annuncio: http://jobs.bemind.me/o/sviluppatoresviluppatrice-servizi-backend-e-non-solo

**Comment by benedettald** [comment]
Ciao! Cerco un  Liferay Analyst Programmer per importante azienda operante nella Digital Transformation!
Qui l'annuncio con tutti i dettagli https://www.experis.it/annuncio-lavoro/analyst-programmer-liferay/500222708
